### ISSUE TITLE
Vertical swipe

### ISSUE THREAD

**Issue by maeyler** [Okuyun/Kuran#2]
Vertical swipe should change current page
Horizontal swipe should change current panel

**Comment by maeyler** [comment]
First implementation:
```
swipe right -- toggleTrans() // T button
swipe left -- toogleFinder() //pink button
swipe down -- prevPage() //down key
swipe up -- nextPage() //up key
```
Full animation is missing

**Comment by maeyler** [comment]
I am not sure if my up-down implementation is correct:
UP key (keyboard), UP button (mouse & touch), UP swipe (touch) all behave the same way: `nextPage`

Is this really intuitive? UP key default is `prevPage `-- I modified the default behavior


_Özetle şunu soruyorum: Up tuşu ve butonu alıştığımız gibi önceki sayfa mı?_
_Yoksa Yukarı kaydırma gibi sonraki sayfa mı olsun?_

**Comment by maeyler** [comment]
This issue is related to natural scrolling:
https://www.huibdijkstra.nl/back-to-the-future-inverted-scrolling-for-windows
https://www.lifewire.com/how-to-change-scrolling-direction-on-mac-2260835

**Comment by gulcu** [comment]
The default for UP key (prevPage) is what I expect, but the choices for left-right keys complicate matters in my opinion.
**Next Page for PDF Readers** (_for a left-to-right alphabet_):
Desktop- DOWN Key , Phone- Swipe UP
My expected 'next page' from Mushaf in Iqra is to proceed to the next page when the LEFT key is pressed, since LEFT is forward in Arabic. Since the reverse is implemented, I think either all (_current situation_) or none (_my personal preference_) should be reversed.

**Comment by maeyler** [comment]
> Vertical swipe should change current page
> Horizontal swipe should change current panel

Current version 4.1b seems to satisfy both goals

**Comment by maeyler** [comment]
UP swipe (touch): `nextPage`

Back to standard behavoir for keys:
UP key (keyboard): `prevPage`
LEFT button (mouse & touch): `prevPage`
No need for UP button

**Comment by maeyler** [comment]
Horizontal swipe is finally implemented in all search panels

It works intuitively: Left and Right swipe cancel each other
3xLeft and 3xRight end up in the starting state
